config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/overons' => 'pages#overons'
  get '/projecten' => 'pages#projecten'
  get '/lnrenoverenfb', 
      to: redirect('https://www.facebook.com/LN-Renoveren-1135736303153132/?fref=ts'), 
      as: 'lnrenoverenlb'
  resources :contacts
  resources :offertes

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, presence: true
  validates :comments, presence: true
end

app/models/offerte.rb
class Offerte < ActiveRecord::Base
    
    validates :gender,
        presence: true
    validates :initials,
        presence: {:message => "Vul uw initialen in"}
    validates :lastname,
        presence: {:message => "Vul uw achternaam in"}
    validates :adres,
        presence: {:message => "Vul uw adres in"}
    validates_format_of :zipcode,
        :with => /(NL-)?(\d{4})\s*([A-Z]{2})/, :message => "De ingevoerde postcode is onjuist", presence: {:message => "Vul uw adres in"}
    validates :city,
        presence: {:message => "Vul uw woonplaats in"}
    validates_numericality_of :telnum,
        :only_integer => true, :message => "Het ingevoerde telefoonnummer is onjuist", presence: {:message => "Vul uw telefoonnummer in"}
    validates_format_of :email,
        :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, :message => "Het ingevoerde emailadres is onjuist", presence: {:message => "Vul uw emailadres in"}
    validates_length_of :subject,
        :minimum => 1, :message => "Het onderwerp moet minimaal 1 en mag maximaal 30 tekens bevatten", :maximum => 30, presence: {:message => "Vul een onderwerp in"}
    validates_length_of :message,
        :minimum => 5, :message => "Het bericht moet minimaal 5 en mag maximaal 1000 tekens bevatten", :maximum => 1000, presence: {:message => "Vul een bericht in"}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
    def new
        @contact = Contact.new
    end
  
    def create
        @contact = Contact.new(contact_params)
        if @contact.save
            name = params[:contact][:name]
            email = params[:contact][:email]
            body = params[:contact][:comments]
            ContactMailer.contact_email(name, email, body).deliver
            flash[:success] = "Bericht verstuurd, u krijgt zo spoedig mogelijk reactie!"
            redirect_to new_contact_path
        else
            render new_contact_path
        end
    end
  
    private
    def contact_params
        params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/offertes_controller.rb
class OffertesController < ApplicationController
  
  def new
      @offerte = Offerte.new
  end
  
    def create
        @offerte = Offerte.new(offerte_params)
        if @offerte.save
            gender = params[:offerte][:gender]
            initials = params[:offerte][:initials]
            lastname = params[:offerte][:lastname]
            adres = params[:offerte][:adres]
            zipcode = params[:offerte][:zipcode]
            city = params[:offerte][:city]
            telnum = params[:offerte][:telnum]
            email = params[:offerte][:email]
            subject = params[:offerte][:subject] 
            message = params[:offerte][:message]
            file = params[:offerte][:file]
            OfferteMailer.offerte_email(gender, initials, lastname, adres, zipcode, city, telnum, email, subject, message, file).deliver
            flash[:success] = "Bedankt voor uw aanvraag, u krijgt zo spoedig mogelijk reactie!"
            redirect_to new_offerte_path
        else
            render new_offerte_path
        end
    end
  
    private
    def offerte_params
        params.require(:offerte).permit(:gender, :initials, :lastname, :adres, :zipcode, :city, :telnum, :email, :subject, :message)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
    def home
    end
  
    def overons
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/new.html.erb
<% if @contact.errors.any? %>
  <script type="text/javascript">
    $(window).load(function(){
      $('#myModal').modal('show');
    });
  </script>
<% end %>
<div class="panel-heading container-fluid text-left">
  <h2>Contact</h2>
</div>
<div class="panel-body text-left">
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In finibus mauris a accumsan ultricies. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras rutrum felis iaculis, viverra eros quis, eleifend ante. Aenean facilisis lobortis rhoncus. Cras rhoncus dignissim magna, eget pretium odio pretium et. Fusce fermentum, erat et dignissim dictum, nibh ligula blandit enim, a pretium mi ligula pellentesque justo. Vestibulum ut nibh sit amet elit elementum rhoncus. Praesent nec risus nunc. In tincidunt diam sed est iaculis, sit amet porttitor ipsum sollicitudin. Ut a aliquam mauris, ut laoreet ex. Aenean sed augue dolor. Curabitur sit amet purus at sem suscipit scelerisque. Phasellus maximus ultrices orci aliquam egestas. Nam vitae ipsum non erat sollicitudin rhoncus sit amet eget mauris. Fusce orci nibh, dignissim auctor tristique non, tempus eget lacus. Cras at augue non erat facilisis bibendum.
    Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam viverra a orci maximus placerat. Quisque laoreet pellentesque metus at lacinia. Nam ornare placerat lorem eget pellentesque. Vestibulum aliquet volutpat leo, non commodo enim rhoncus nec. Nam euismod sapien vitae dictum feugiat. Maecenas efficitur, sapien ut porta condimentum, augue massa egestas eros, ut imperdiet odio dolor non dolor. Nunc malesuada ex id maximus cursus. Proin tempus ipsum ut ipsum bibendum, non fermentum odio pretium. Pellentesque vitae lectus et mi eleifend fermentum. In tempor aliquet est, eget vulputate lacus vestibulum sit amet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In finibus mauris a accumsan ultricies. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras rutrum felis iaculis, viverra eros quis, eleifend ante. Aenean facilisis lobortis rhoncus. Cras rhoncus dignissim magna, eget pretium odio pretium et. Fusce fermentum, erat et dignissim dictum, nibh ligula blandit enim, a pretium mi ligula pellentesque justo. Vestibulum ut nibh sit amet elit elementum rhoncus. Praesent nec risus nunc. In tincidunt diam sed est iaculis, sit amet porttitor ipsum sollicitudin. Ut a aliquam mauris, ut laoreet ex. Aenean sed augue dolor. Curabitur sit amet purus at sem suscipit scelerisque. Phasellus maximus ultrices orci aliquam egestas. Nam vitae ipsum non erat sollicitudin rhoncus sit amet eget mauris. Fusce orci nibh, dignissim auctor tristique non, tempus eget lacus. Cras at augue non erat facilisis bibendum.
  </p>
  <button type="button" class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#myModal">Open Contactformulier</button>
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Contactformulier</h4>
        </div>
        <div class="modal-body">
          <div class="well">
            <% if @contact.errors.any? %>
              <ul>
                <% @contact.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            <% end %>
            <p class="text-right">Alle velden met een * zijn verplicht</p>
            <%= form_for @contact do |f| %>
              <div class="form-group">
                <%= f.label :'Naam*' %>
                <%= f.text_field :name, class: 'form-control', placeholder: 'Naam' %>
              </div>
              <div class="form-group">
                <%= f.label :'Uw e-mailadres*' %>
                <%= f.email_field :email, class: 'form-control', placeholder: 'jouwadres@voorbeeld.nl' %>
              </div>
              <div class="form-group">
                <%= f.label :'Uw bericht*' %>
                <%= f.text_area :comments, class: 'form-control textbox', placeholder: 'Uw bericht' %>
              </div>
            </div>
            <%= f.submit 'Versturen', class: 'btn btn-success' do %>
              <%= "data-dismiss='modal'".html_safe %>
            <% end %>
            <button type="button" class="btn btn-danger pull-right" data-dismiss="modal" >Annuleren</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>LN-Renoveren</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target="nav" data-offset="50">
  
<div class="container-fluid header">
  <div class="row">
    <div class="img-responsive">
        <!--<%= image_tag('bannerexample.png') %>-->
    </div>
  </div>
</div>

<nav class="navbar navbar-default navbar-static-top" role="navigation" data-spy="affix" data-offset-top="200">
  <div class='container-fluid'>
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: 'navbar-brand rootbutton' do %> 
          <i class="fa fa-home fa-lg" aria-hidden="true"></i>
          Home
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
      <ul class="nav navbar-nav navbar-left">
        <li id='navbar-button'>
          <%= link_to overons_path, class: 'overonsbutton' do %>
            <i class="fa fa-users" aria-hidden="true"></i>
            Over Ons
          <% end %>
        </li>
        <li id='navbar-button'>
          <%= link_to projecten_path, class: 'projectenbutton' do %>
            <i class="fa fa-suitcase" aria-hidden="true"></i>
            Projecten
          <% end %>
        </li>
        <li id='navbar-button'>
          <%= link_to new_offerte_path, class: 'offertebutton' do %>
            <i class="fa fa-file-text-o" aria-hidden="true"></i>
            Offerte
          <% end %>
        </li>    
        <li id='navbar-button'>
          <%= link_to new_contact_path, class: 'contactbutton' do %>
            <i class="fa fa-envelope" aria-hidden="true"></i>
            Contact
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

<div class="container-fluid">
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "alert alert-#{key}" %>
  <% end %>
  <%= yield %>
</div>

<footer class="container-fluid text-center">
  <div class="hidden-xs hidden-sm col-md-3 col-lg-3">
  
  </div>
  <div class="hidden-xs hidden-sm col-md-6 col-lg-6">
    <p>(06) 403 511 38 | renoveren.ln@gmail.com | www.LN-Renoveren.nl</p>
  </div>
  <!--<div class="hidden-md hidden-lg col-xs-12 col-sm-12" style="padding-bottom:0em;">
    <p>(06) 403 511 38<br>renoveren.ln@gmail.com<br>www.LN-Renoveren.nl</p>
  </div>-->
  <div class="hidden-xs hidden-sm col-md-3 col-lg-3">
    
  </div>
</footer>

</body>
</html>

app/views/offertes/new.html.erb
<% if @offerte.errors.any? %>
  <script type="text/javascript">
    $(window).load(function(){
      $('#myModal').modal('show');
    });
  </script>
<% end %>
<div class="panel-heading container-fluid text-left">
  <h2>Offerte Aanvraag</h2>
</div>
<div class="panel-body text-left">
  <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In finibus mauris a accumsan ultricies. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras rutrum felis iaculis, viverra eros quis, eleifend ante. Aenean facilisis lobortis rhoncus. Cras rhoncus dignissim magna, eget pretium odio pretium et. Fusce fermentum, erat et dignissim dictum, nibh ligula blandit enim, a pretium mi ligula pellentesque justo. Vestibulum ut nibh sit amet elit elementum rhoncus. Praesent nec risus nunc. In tincidunt diam sed est iaculis, sit amet porttitor ipsum sollicitudin. Ut a aliquam mauris, ut laoreet ex. Aenean sed augue dolor. Curabitur sit amet purus at sem suscipit scelerisque. Phasellus maximus ultrices orci aliquam egestas. Nam vitae ipsum non erat sollicitudin rhoncus sit amet eget mauris. Fusce orci nibh, dignissim auctor tristique non, tempus eget lacus. Cras at augue non erat facilisis bibendum.
    Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam viverra a orci maximus placerat. Quisque laoreet pellentesque metus at lacinia. Nam ornare placerat lorem eget pellentesque. Vestibulum aliquet volutpat leo, non commodo enim rhoncus nec. Nam euismod sapien vitae dictum feugiat. Maecenas efficitur, sapien ut porta condimentum, augue massa egestas eros, ut imperdiet odio dolor non dolor. Nunc malesuada ex id maximus cursus. Proin tempus ipsum ut ipsum bibendum, non fermentum odio pretium. Pellentesque vitae lectus et mi eleifend fermentum. In tempor aliquet est, eget vulputate lacus vestibulum sit amet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. In finibus mauris a accumsan ultricies. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras rutrum felis iaculis, viverra eros quis, eleifend ante. Aenean facilisis lobortis rhoncus. Cras rhoncus dignissim magna, eget pretium odio pretium et. Fusce fermentum, erat et dignissim dictum, nibh ligula blandit enim, a pretium mi ligula pellentesque justo. Vestibulum ut nibh sit amet elit elementum rhoncus. Praesent nec risus nunc. In tincidunt diam sed est iaculis, sit amet porttitor ipsum sollicitudin. Ut a aliquam mauris, ut laoreet ex. Aenean sed augue dolor. Curabitur sit amet purus at sem suscipit scelerisque. Phasellus maximus ultrices orci aliquam egestas. Nam vitae ipsum non erat sollicitudin rhoncus sit amet eget mauris. Fusce orci nibh, dignissim auctor tristique non, tempus eget lacus. Cras at augue non erat facilisis bibendum.
  </p>
  <button type="button" class="btn btn-primary btn-lg pull-right" data-toggle="modal" data-target="#myModal">Vraag hier uw offerte aan</button>
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Offerte-aanvraagformulier</h4>
        </div>
        <div class="modal-body">
          <div class="well">
            <% if @offerte.errors.any? %>
              <ul>
                <% @offerte.errors.each_with_index do |msg, i| %>
                  <li><%= msg[1] %></li>
                  <li><%= i %></li>
                <% end %>
              </ul>
            <% end %>
            <p class="text-right">Alle velden met een * zijn verplicht</p>
            <%= form_for @offerte, :html => { :multipart => true } do |f| %>
              <div class="form-group">
                <%= f.label :'Aanhef*' %><br>
                <%= f.label :gender, "Meneer", :value => 'male' %>
                <%= f.radio_button :gender, 'male', :checked => true %>
                <%= f.label :gender, "Mevrouw", :value => 'female' %>
                <%= f.radio_button :gender, 'female' %>
              </div>
              <div class="form-group">
                <%= f.label :'Voorletter(s)*' %>
                <%= f.text_field :initials, class: 'form-control', placeholder: 'Voorletters' %>
              </div>
              <div class="form-group">
                <%= f.label :'Achternaam*' %>
                <%= f.text_field :lastname, class: 'form-control', placeholder: 'Achternaam' %>
              </div>
              <div class="form-group">
                <%= f.label :'Adres*' %>
                <%= f.text_field :adres, class: 'form-control', placeholder: 'Straat + huisnummer' %>
              </div>
              <div class="form-group">
                <%= f.label :'Postcode*' %>
                <%= f.text_field :zipcode, class: 'form-control', placeholder: '1234AB' %>
              </div>
              <div class="form-group">
                <%= f.label :'Woonplaats*' %>
                <%= f.text_field :city, class: 'form-control', placeholder: 'Woonplaats' %>
              </div>
              <div class="form-group">
                <%= f.label :'Telefoonnummer*' %>
                <%= f.text_field :telnum, class: 'form-control', placeholder: '0612345678' %>
              </div>
              <div class="form-group">
                <%= f.label :'Emailadres*' %>
                <%= f.text_field :email, class: 'form-control', placeholder: 'jouwadres@voorbeeld.nl' %>
              </div>
              <div class="form-group">
                <%= f.label :'Onderwerp*' %>
                <%= f.text_field :subject, class: 'form-control', placeholder: 'Onderwerp' %>
              </div>
              <div class="form-group">
                <%= f.label :'Bericht*' %>
                <%= f.text_area :message, class: 'form-control textbox', placeholder: 'Wees zo specifiek mogelijk voor een zo nauwkeurig mogelijk aangemeten offerte' %>
              </div>
              <div>
                <%= f.label :'Afbeelding toevoegen (optioneel)' %>
                <%= f.file_field :file, onchange: "validateFiles(this);", data: { max_file_size: 5.megabytes }, class: 'form-control' %>
              </div>
            </div>
            <%= f.submit 'Bevestig Aanvraag', class: 'btn btn-success' do %>
              <%= "data-dismiss='modal'".html_safe %>
            <% end %>
            <button type="button" class="btn btn-danger pull-right" data-dismiss="modal">Annuleren</button>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="panel-heading container-fluid text-left">
    <h2>Home</h2>
</div>
<div class="panel-body text-left">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In finibus mauris a accumsan ultricies. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras rutrum felis iaculis, viverra eros quis, eleifend ante. Aenean facilisis lobortis rhoncus. Cras rhoncus dignissim magna, eget pretium odio pretium et. Fusce fermentum, erat et dignissim dictum, nibh ligula blandit enim, a pretium mi ligula pellentesque justo. Vestibulum ut nibh sit amet elit elementum rhoncus. Praesent nec risus nunc. In tincidunt diam sed est iaculis, sit amet porttitor ipsum sollicitudin. Ut a aliquam mauris, ut laoreet ex. Aenean sed augue dolor. Curabitur sit amet purus at sem suscipit scelerisque. Phasellus maximus ultrices orci aliquam egestas. Nam vitae ipsum non erat sollicitudin rhoncus sit amet eget mauris. Fusce orci nibh, dignissim auctor tristique non, tempus eget lacus. Cras at augue non erat facilisis bibendum.
        Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam viverra a orci maximus placerat. Quisque laoreet pellentesque metus at lacinia. Nam ornare placerat lorem eget pellentesque. Vestibulum aliquet volutpat leo, non commodo enim rhoncus nec. Nam euismod sapien vitae dictum feugiat. Maecenas efficitur, sapien ut porta condimentum, augue massa egestas eros, ut imperdiet odio dolor non dolor. Nunc malesuada ex id maximus cursus. Proin tempus ipsum ut ipsum bibendum, non fermentum odio pretium. Pellentesque vitae lectus et mi eleifend fermentum. In tempor aliquet est, eget vulputate lacus vestibulum sit amet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In finibus mauris a accumsan ultricies. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras rutrum felis iaculis, viverra eros quis, eleifend ante. Aenean facilisis lobortis rhoncus. Cras rhoncus dignissim magna, eget pretium odio pretium et. Fusce fermentum, erat et dignissim dictum, nibh ligula blandit enim, a pretium mi ligula pellentesque justo. Vestibulum ut nibh sit amet elit elementum rhoncus. Praesent nec risus nunc. In tincidunt diam sed est iaculis, sit amet porttitor ipsum sollicitudin. Ut a aliquam mauris, ut laoreet ex. Aenean sed augue dolor. Curabitur sit amet purus at sem suscipit scelerisque. Phasellus maximus ultrices orci aliquam egestas. Nam vitae ipsum non erat sollicitudin rhoncus sit amet eget mauris. Fusce orci nibh, dignissim auctor tristique non, tempus eget lacus. Cras at augue non erat facilisis bibendum.
    </p>
</div>

app/views/pages/offerte.html.erb
<div class="panel-heading container-fluid text-left">
    <h2>Home</h2>
</div>
<div class="panel-body text-left">
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In finibus mauris a accumsan ultricies. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras rutrum felis iaculis, viverra eros quis, eleifend ante. Aenean facilisis lobortis rhoncus. Cras rhoncus dignissim magna, eget pretium odio pretium et. Fusce fermentum, erat et dignissim dictum, nibh ligula blandit enim, a pretium mi ligula pellentesque justo. Vestibulum ut nibh sit amet elit elementum rhoncus. Praesent nec risus nunc. In tincidunt diam sed est iaculis, sit amet porttitor ipsum sollicitudin. Ut a aliquam mauris, ut laoreet ex. Aenean sed augue dolor. Curabitur sit amet purus at sem suscipit scelerisque. Phasellus maximus ultrices orci aliquam egestas. Nam vitae ipsum non erat sollicitudin rhoncus sit amet eget mauris. Fusce orci nibh, dignissim auctor tristique non, tempus eget lacus. Cras at augue non erat facilisis bibendum.
        Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam viverra a orci maximus placerat. Quisque laoreet pellentesque metus at lacinia. Nam ornare placerat lorem eget pellentesque. Vestibulum aliquet volutpat leo, non commodo enim rhoncus nec. Nam euismod sapien vitae dictum feugiat. Maecenas efficitur, sapien ut porta condimentum, augue massa egestas eros, ut imperdiet odio dolor non dolor. Nunc malesuada ex id maximus cursus. Proin tempus ipsum ut ipsum bibendum, non fermentum odio pretium. Pellentesque vitae lectus et mi eleifend fermentum. In tempor aliquet est, eget vulputate lacus vestibulum sit amet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. In finibus mauris a accumsan ultricies. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras rutrum felis iaculis, viverra eros quis, eleifend ante. Aenean facilisis lobortis rhoncus. Cras rhoncus dignissim magna, eget pretium odio pretium et. Fusce fermentum, erat et dignissim dictum, nibh ligula blandit enim, a pretium mi ligula pellentesque justo. Vestibulum ut nibh sit amet elit elementum rhoncus. Praesent nec risus nunc. In tincidunt diam sed est iaculis, sit amet porttitor ipsum sollicitudin. Ut a aliquam mauris, ut laoreet ex. Aenean sed augue dolor. Curabitur sit amet purus at sem suscipit scelerisque. Phasellus maximus ultrices orci aliquam egestas. Nam vitae ipsum non erat sollicitudin rhoncus sit amet eget mauris. Fusce orci nibh, dignissim auctor tristique non, tempus eget lacus. Cras at augue non erat facilisis bibendum.
    </p>
</div>

app/views/pages/onepage.html.erb
<div id="sectionhome" class="container-fluid">
</div>
<div id="sectionaboutus" class="container-fluid">
</div>
<div id="sectionprojects" class="container-fluid">
</div>
<div id="sectionofferte" class="container-fluid">
</div>
<div id="sectioncontact" class="container-fluid">
</div>

app/views/pages/projecten.html.erb
<div class="panel-heading container-fluid text-left">
  <h2>Projecten</h2>
</div>
<div class="panel-body text-left" id="panelprojecten">
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <!--<li data-target="#myCarousel" data-slide-to="3"></li>-->
    </ol>
    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag('vb1vn.png') %>
      </div>
      <div class="item">
        <%= image_tag('vb2vn.png') %>
      </div>
      <div class="item">
        <%= image_tag('vb3vn.png') %>
      </div>
      <!--<div class="item">
      <%= image_tag('image.png') %>
      </div>-->
    </div>
    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>